#!/bin/bash -e

#
# setup-shareef12-desktop-user
#
# This script will configure i3 and user-specific settings.
#

function install_conffile {
    install --verbose --backup -D -m 0644 "$1" "$2"
}

# Install configuration files
install_conffile /etc/shareef12-desktop/devscripts ~/.devscripts
install_conffile /etc/shareef12-desktop/gdbinit ~/.gdbinit
install_conffile /etc/shareef12-desktop/i3config ~/.config/i3/config
install_conffile /etc/shareef12-desktop/i3status.conf ~/.config/i3status/config
install_conffile /etc/shareef12-desktop/shareef12-desktop.colorscheme ~/.config/qterminal.org/color-schemes/shareef12-desktop.colorscheme
install_conffile /etc/shareef12-desktop/vimrc ~/.vimrc

# Update the qterminal color scheme and settings
sed -i \
    -e 's/^AskOnExit=.*$/AskOnExit=false/'                 \
    -e 's/^colorScheme=.*$/colorScheme=shareef12-desktop/' \
    -e 's/^fontSize=.*$/fontSize=10/'                      \
    ~/.config/qterminal.org/qterminal.ini

# Update bashrc configuration
if ! grep -q 'Configured by shareef12-desktop' ~/.bashrc; then
    echo "Configuring bashrc..."
    cat /etc/shareef12-desktop/bashrc >> ~/.bashrc
    source ~/.bashrc
fi

# Configure a default git user
if ! git config --get user.name > /dev/null; then
    echo "Configuring git..."
    git config --global user.name shareef12
    git config --global user.email shareef12@twelvetacos.com
fi

# Generate an SSH key
if [ ! -f ~/.ssh/id_rsa ] && [ ! -f ~/.ssh/id_ecdsa ]; then
    echo "Configuring SSH..."
    ssh-keygen -t ecdsa -C "${USER}@$(hostname)" -N '' -f ~/.ssh/id_ecdsa
    cp ~/.ssh/id_ecdsa.pub ~/.ssh/authorized_keys
fi

echo "Updating filesystem permissions..."
chmod 750 ~/
chmod 700 ~/.ssh

echo "Restarting i3..."
i3-msg reload
i3-msg restart
